-- ============================================================================
-- Migration 045: Access Settings (merge of network + search_config)
-- ============================================================================
--
-- An Access Settings is the consumer's plan for one of their bots:
--   - a list of catalogues the bot is allowed to consume
--   - a max_price_eur ceiling that protects against publisher price hikes
--
-- An API key is now a (subscription, access_settings) pair. The bot identity
-- is carried by the access_settings (not the key) so multiple keys for the
-- same plan share the bot.
--
-- Sub-manager revenue (the historical 7% line) is rerouted via a new
-- `workspaces.referral_workspace_id` column. When NULL, the sub_manager
-- ledger row keeps `recipient_workspace_id = NULL` (absorbed by the platform
-- at reconciliation).
--
-- Catalogue eligibility for an access_settings:
--   - catalog.status = 'active'  (marketplace), or
--   - catalog.workspace_id = access_settings.workspace_id  (own private cat).
--
-- ⚠️ Destructive (MVP): api_keys is TRUNCATED. networks and network_catalogs
-- are dropped. Existing keys must be re-issued through the new flow.
-- credit_transactions.api_key_id is ON DELETE SET NULL so the ledger survives.
--
-- All statements are idempotent so a partial-applied remote can re-run this
-- without manual reconciliation.
-- ============================================================================

BEGIN;


-- ============================================================================
-- 1. workspaces.referral_workspace_id
-- ============================================================================

ALTER TABLE public.workspaces
  ADD COLUMN IF NOT EXISTS referral_workspace_id UUID NULL
    REFERENCES public.workspaces(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_workspaces_referral
  ON public.workspaces(referral_workspace_id)
  WHERE referral_workspace_id IS NOT NULL;

COMMENT ON COLUMN public.workspaces.referral_workspace_id IS
  'Sub-manager / reseller workspace that receives the sub_manager revenue '
  'share for every debit generated by THIS workspace''s subscriptions. NULL '
  'means there is no referral — the corresponding ledger row keeps '
  'recipient_workspace_id NULL and is absorbed by the platform.';


-- ============================================================================
-- 2. access_settings
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.access_settings (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  public_id       TEXT NOT NULL UNIQUE
                    CHECK (starts_with(public_id, 'as_')),
  workspace_id    UUID NOT NULL REFERENCES public.workspaces(id) ON DELETE CASCADE,
  bot_id          UUID NOT NULL REFERENCES public.bots(id)       ON DELETE RESTRICT,
  name            TEXT NOT NULL,
  max_price_eur   NUMERIC(10,4) NOT NULL
                    CHECK (max_price_eur >= 0),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (workspace_id, name)
);

CREATE INDEX IF NOT EXISTS idx_access_settings_workspace ON public.access_settings(workspace_id);
CREATE INDEX IF NOT EXISTS idx_access_settings_bot       ON public.access_settings(bot_id);

COMMENT ON TABLE public.access_settings IS
  'Consumer plan: a named (bot, catalogues, max_price) tuple owned by a '
  'workspace. API keys reference one access_settings — its bot is the '
  'identity claimed at /licenses time, its catalogues are the allowlist, '
  'its max_price_eur caps publisher price hikes.';


-- ============================================================================
-- 3. access_settings_catalogs (junction, no invite lifecycle)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.access_settings_catalogs (
  access_settings_id UUID NOT NULL REFERENCES public.access_settings(id) ON DELETE CASCADE,
  catalog_id         UUID NOT NULL REFERENCES public.catalogs(id)        ON DELETE CASCADE,
  added_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (access_settings_id, catalog_id)
);

CREATE INDEX IF NOT EXISTS idx_access_settings_catalogs_catalog
  ON public.access_settings_catalogs(catalog_id);

COMMENT ON TABLE public.access_settings_catalogs IS
  'Catalogues bundled into an access_settings. Eligibility is enforced by a '
  'BEFORE INSERT trigger: catalog must either be on the marketplace '
  '(status=active) or belong to the same workspace as the access_settings.';


-- ============================================================================
-- 4. Trigger: bot must be in workspace_bots(workspace_id, bot_id)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.validate_access_settings_bot()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.workspace_bots
    WHERE workspace_id = NEW.workspace_id
      AND bot_id       = NEW.bot_id
  ) THEN
    RAISE EXCEPTION
      'bot_not_in_workspace: workspace=% bot=%',
      NEW.workspace_id, NEW.bot_id
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_access_settings_validate_bot ON public.access_settings;
CREATE TRIGGER trg_access_settings_validate_bot
  BEFORE INSERT OR UPDATE OF workspace_id, bot_id ON public.access_settings
  FOR EACH ROW EXECUTE FUNCTION public.validate_access_settings_bot();


-- ============================================================================
-- 5. Trigger: catalog eligibility (marketplace OR own workspace)
-- ============================================================================

CREATE OR REPLACE FUNCTION public.validate_access_settings_catalog()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_consumer_ws  UUID;
  v_catalog_ws   UUID;
  v_catalog_status TEXT;
BEGIN
  SELECT workspace_id INTO v_consumer_ws
  FROM public.access_settings
  WHERE id = NEW.access_settings_id;

  SELECT workspace_id, status INTO v_catalog_ws, v_catalog_status
  FROM public.catalogs
  WHERE id = NEW.catalog_id;

  IF v_catalog_ws IS NULL THEN
    RAISE EXCEPTION 'catalog_not_found: catalog=%', NEW.catalog_id
      USING ERRCODE = 'check_violation';
  END IF;

  IF v_catalog_status <> 'active' AND v_catalog_ws <> v_consumer_ws THEN
    RAISE EXCEPTION
      'catalog_not_eligible: catalog=% (status=%) workspace=% access_settings_workspace=%',
      NEW.catalog_id, v_catalog_status, v_catalog_ws, v_consumer_ws
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_access_settings_catalogs_validate ON public.access_settings_catalogs;
CREATE TRIGGER trg_access_settings_catalogs_validate
  BEFORE INSERT ON public.access_settings_catalogs
  FOR EACH ROW EXECUTE FUNCTION public.validate_access_settings_catalog();


-- ============================================================================
-- 6. RLS
-- ============================================================================

ALTER TABLE public.access_settings          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.access_settings_catalogs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "workspace_members_read_access_settings" ON public.access_settings;
CREATE POLICY "workspace_members_read_access_settings" ON public.access_settings
  FOR SELECT
  USING (
    workspace_id IN (
      SELECT workspace_id FROM public.workspace_members
      WHERE user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "workspace_admins_write_access_settings" ON public.access_settings;
CREATE POLICY "workspace_admins_write_access_settings" ON public.access_settings
  FOR ALL
  USING (
    workspace_id IN (
      SELECT workspace_id FROM public.workspace_members
      WHERE user_id = auth.uid() AND role IN ('owner', 'admin')
    )
  )
  WITH CHECK (
    workspace_id IN (
      SELECT workspace_id FROM public.workspace_members
      WHERE user_id = auth.uid() AND role IN ('owner', 'admin')
    )
  );

DROP POLICY IF EXISTS "members_read_access_settings_catalogs" ON public.access_settings_catalogs;
CREATE POLICY "members_read_access_settings_catalogs" ON public.access_settings_catalogs
  FOR SELECT
  USING (
    access_settings_id IN (
      SELECT a.id FROM public.access_settings a
      JOIN public.workspace_members wm ON wm.workspace_id = a.workspace_id
      WHERE wm.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "admins_write_access_settings_catalogs" ON public.access_settings_catalogs;
CREATE POLICY "admins_write_access_settings_catalogs" ON public.access_settings_catalogs
  FOR ALL
  USING (
    access_settings_id IN (
      SELECT a.id FROM public.access_settings a
      JOIN public.workspace_members wm ON wm.workspace_id = a.workspace_id
      WHERE wm.user_id = auth.uid() AND wm.role IN ('owner', 'admin')
    )
  )
  WITH CHECK (
    access_settings_id IN (
      SELECT a.id FROM public.access_settings a
      JOIN public.workspace_members wm ON wm.workspace_id = a.workspace_id
      WHERE wm.user_id = auth.uid() AND wm.role IN ('owner', 'admin')
    )
  );


-- ============================================================================
-- 7. updated_at trigger on access_settings
-- ============================================================================

CREATE OR REPLACE FUNCTION public.touch_access_settings_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_access_settings_touch_updated_at ON public.access_settings;
CREATE TRIGGER trg_access_settings_touch_updated_at
  BEFORE UPDATE ON public.access_settings
  FOR EACH ROW EXECUTE FUNCTION public.touch_access_settings_updated_at();


-- ============================================================================
-- 8. api_keys: swap network_id → access_settings_id, replace bot trigger
-- ============================================================================

DROP TRIGGER  IF EXISTS trg_api_keys_validate_bot_in_network   ON public.api_keys;
DROP FUNCTION IF EXISTS public.validate_api_key_bot_in_network();

TRUNCATE TABLE public.api_keys CASCADE;

DROP INDEX IF EXISTS public.idx_api_keys_network;

ALTER TABLE public.api_keys
  DROP COLUMN IF EXISTS network_id;

ALTER TABLE public.api_keys
  ADD COLUMN IF NOT EXISTS access_settings_id UUID
    REFERENCES public.access_settings(id) ON DELETE RESTRICT;

-- Promote to NOT NULL (api_keys has been truncated above so this is safe).
ALTER TABLE public.api_keys
  ALTER COLUMN access_settings_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_api_keys_access_settings
  ON public.api_keys(access_settings_id);

COMMENT ON COLUMN public.api_keys.access_settings_id IS
  'Access settings bound to this key. Carries the bot identity and the '
  'catalogue allowlist + max_price cap consumed at /licenses time.';

CREATE OR REPLACE FUNCTION public.validate_api_key_bot_matches_access_settings()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  v_expected_bot UUID;
BEGIN
  SELECT bot_id INTO v_expected_bot
  FROM public.access_settings
  WHERE id = NEW.access_settings_id;

  IF v_expected_bot IS NULL THEN
    RAISE EXCEPTION 'access_settings_not_found: access_settings=%',
      NEW.access_settings_id
      USING ERRCODE = 'check_violation';
  END IF;

  IF v_expected_bot <> NEW.bot_id THEN
    RAISE EXCEPTION
      'bot_mismatch: api_key.bot=% access_settings.bot=%',
      NEW.bot_id, v_expected_bot
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_api_keys_validate_bot_matches_access_settings ON public.api_keys;
CREATE TRIGGER trg_api_keys_validate_bot_matches_access_settings
  BEFORE INSERT OR UPDATE OF bot_id, access_settings_id ON public.api_keys
  FOR EACH ROW EXECUTE FUNCTION public.validate_api_key_bot_matches_access_settings();


-- ============================================================================
-- 9. Drop networks + network_catalogs (CASCADE drops the access_grants FK if any)
-- ============================================================================

DROP TABLE IF EXISTS public.network_catalogs CASCADE;
DROP TABLE IF EXISTS public.networks         CASCADE;
DROP TYPE  IF EXISTS public.network_catalog_status;


-- ============================================================================
-- 10. authorize_and_debit_batch — rewrite for access_settings
-- ============================================================================
--
-- Differences vs. the previous (network-based) implementation:
--
--   * Resolution joins access_settings (not networks). Reads bot, ua_pattern,
--     max_price_eur, and the referral_workspace_id of the CONSUMER's workspace
--     (which is the new sub-manager recipient).
--
--   * Membership check uses access_settings_catalogs (no status filter — the
--     row is the membership; there is no invite lifecycle anymore).
--
--   * Max-price guard: re-fetches catalog.price_eur and skips silently when it
--     exceeds access_settings.max_price_eur. Closes the TOCTOU window between
--     the TS-side filter and the RPC call.
--
--   * sub_manager ledger row: recipient_workspace_id = referral_workspace_id
--     (may be NULL when the consumer workspace has no referral set).
--
-- p_debits item shape (TS callers must conform — unchanged from migration 042):
--   {
--     publisher_workspace_id  uuid,
--     catalog_id              uuid,
--     url                     text,
--     price_eur               numeric,   -- TS hint; the RPC re-reads from `catalogs`
--     ttl_minutes             integer,
--     amount_content_owner    numeric,
--     amount_sub_manager      numeric,
--     amount_platform_fee     numeric
--   }
-- ============================================================================

CREATE OR REPLACE FUNCTION public.authorize_and_debit_batch(
  p_api_key_id UUID,
  p_debits     JSONB
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_consumer_ws    UUID;
  v_subscription   UUID;
  v_access_set     UUID;
  v_bot            UUID;
  v_ua_pattern     TEXT;
  v_max_price      NUMERIC;
  v_referral_ws    UUID;
  v_debit          JSONB;
  v_balance        NUMERIC;
  v_new_balance    NUMERIC;
  v_total_cost     NUMERIC := 0;
  v_grants         JSONB   := '[]'::JSONB;
  v_cached_grant   public.access_grants%ROWTYPE;
  v_grant_id       UUID;
  v_expires_at     TIMESTAMPTZ;
  v_url            TEXT;
  v_price          NUMERIC;
  v_actual_price   NUMERIC;
  v_ttl            INTEGER;
  v_publisher_id   UUID;
  v_catalog_id     UUID;
  v_amount_co      NUMERIC;
  v_amount_sm      NUMERIC;
  v_amount_pf      NUMERIC;
BEGIN
  SELECT ak.workspace_id, ak.subscription_id, ak.access_settings_id, ak.bot_id,
         b.ua_pattern, as_t.max_price_eur, ws.referral_workspace_id
    INTO v_consumer_ws, v_subscription, v_access_set, v_bot,
         v_ua_pattern, v_max_price, v_referral_ws
  FROM public.api_keys        ak
  JOIN public.bots            b    ON b.id    = ak.bot_id
  JOIN public.access_settings as_t ON as_t.id = ak.access_settings_id
  JOIN public.workspaces      ws   ON ws.id   = ak.workspace_id
  WHERE ak.id = p_api_key_id;

  IF v_consumer_ws IS NULL THEN
    RAISE EXCEPTION 'api_key_not_found: api_key=%', p_api_key_id;
  END IF;

  -- PASS 1: per-URL cache check + membership check + max_price guard.
  FOR v_debit IN SELECT * FROM jsonb_array_elements(p_debits)
  LOOP
    v_url        := v_debit->>'url';
    v_catalog_id := (v_debit->>'catalog_id')::UUID;

    SELECT * INTO v_cached_grant
    FROM public.access_grants
    WHERE api_key_id = p_api_key_id
      AND url        = v_url
      AND expires_at > now();

    IF FOUND THEN
      v_grants := v_grants || jsonb_build_object(
        'url',        v_url,
        'grant_id',   v_cached_grant.id,
        'expires_at', v_cached_grant.expires_at,
        'cached',     true
      );
      CONTINUE;
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM public.access_settings_catalogs
      WHERE access_settings_id = v_access_set
        AND catalog_id         = v_catalog_id
    ) THEN
      CONTINUE;
    END IF;

    SELECT price_eur INTO v_actual_price
    FROM public.catalogs WHERE id = v_catalog_id;

    IF v_actual_price IS NULL OR v_actual_price > v_max_price THEN
      CONTINUE;
    END IF;

    v_price := v_actual_price;
    v_total_cost := v_total_cost + v_price;
    v_grants := v_grants || jsonb_build_object(
      'url',                  v_url,
      'grant_id',             NULL,
      'expires_at',           NULL,
      'cached',               false,
      '_price',               v_price,
      '_publisher',           v_debit->>'publisher_workspace_id',
      '_catalog',             v_catalog_id::TEXT,
      '_ttl',                 (v_debit->>'ttl_minutes')::INTEGER,
      '_amount_content',      (v_debit->>'amount_content_owner')::NUMERIC,
      '_amount_sub_manager',  (v_debit->>'amount_sub_manager')::NUMERIC,
      '_amount_platform',     (v_debit->>'amount_platform_fee')::NUMERIC
    );
  END LOOP;

  IF v_total_cost <= 0 THEN
    SELECT balance_eur INTO v_balance
    FROM public.subscriptions WHERE id = v_subscription;

    IF NOT FOUND THEN
      RAISE EXCEPTION 'subscription_not_found: subscription=%', v_subscription;
    END IF;

    v_grants := (
      SELECT COALESCE(jsonb_agg(
        g - '_price' - '_publisher' - '_catalog' - '_ttl'
          - '_amount_content' - '_amount_sub_manager' - '_amount_platform'
      ), '[]'::JSONB)
      FROM jsonb_array_elements(v_grants) AS g
    );

    RETURN jsonb_build_object(
      'success',     true,
      'new_balance', v_balance,
      'grants',      v_grants
    );
  END IF;

  -- PASS 2: lock subscription, balance check, debit, write grants + ledger.
  SELECT balance_eur INTO v_balance
  FROM public.subscriptions
  WHERE id = v_subscription
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'subscription_not_found: subscription=%', v_subscription;
  END IF;

  IF v_balance < v_total_cost THEN
    RETURN jsonb_build_object(
      'success',  false,
      'reason',   'insufficient_balance',
      'balance',  v_balance,
      'required', v_total_cost
    );
  END IF;

  v_new_balance := v_balance - v_total_cost;
  UPDATE public.subscriptions
    SET balance_eur = v_new_balance
  WHERE id = v_subscription;

  FOR v_debit IN SELECT * FROM jsonb_array_elements(v_grants)
  LOOP
    IF (v_debit->>'cached')::BOOLEAN THEN CONTINUE; END IF;

    v_url          := v_debit->>'url';
    v_price        := (v_debit->>'_price')::NUMERIC;
    v_publisher_id := (v_debit->>'_publisher')::UUID;
    v_catalog_id   := (v_debit->>'_catalog')::UUID;
    v_ttl          := (v_debit->>'_ttl')::INTEGER;
    v_amount_co    := (v_debit->>'_amount_content')::NUMERIC;
    v_amount_sm    := (v_debit->>'_amount_sub_manager')::NUMERIC;
    v_amount_pf    := (v_debit->>'_amount_platform')::NUMERIC;
    v_expires_at   := now() + (v_ttl || ' minutes')::INTERVAL;

    INSERT INTO public.access_grants (
      consumer_workspace_id, publisher_workspace_id, api_key_id,
      url, catalog_id, bot_id, ua_pattern, price_eur, expires_at
    ) VALUES (
      v_consumer_ws, v_publisher_id, p_api_key_id,
      v_url, v_catalog_id, v_bot, v_ua_pattern, v_price, v_expires_at
    )
    ON CONFLICT (api_key_id, url) DO UPDATE
      SET expires_at = EXCLUDED.expires_at,
          catalog_id = EXCLUDED.catalog_id,
          bot_id     = EXCLUDED.bot_id,
          ua_pattern = EXCLUDED.ua_pattern,
          price_eur  = EXCLUDED.price_eur
    RETURNING id INTO v_grant_id;

    INSERT INTO public.credit_transactions
      (consumer_workspace_id, recipient_workspace_id, publisher_workspace_id,
       role, amount_eur,
       content_url, catalog_id, grant_id, bot_id, subscription_id, api_key_id, description)
    VALUES
      (v_consumer_ws, NULL,            v_publisher_id,
       'debit', -v_price,
       v_url, v_catalog_id, v_grant_id, v_bot, v_subscription, p_api_key_id,
       'Content access grant'),
      (v_consumer_ws, v_publisher_id,  v_publisher_id,
       'content_owner', v_amount_co,
       v_url, v_catalog_id, v_grant_id, v_bot, v_subscription, p_api_key_id,
       'Content owner share'),
      (v_consumer_ws, v_referral_ws,   v_publisher_id,
       'sub_manager', v_amount_sm,
       v_url, v_catalog_id, v_grant_id, v_bot, v_subscription, p_api_key_id,
       'Sub-manager share'),
      (v_consumer_ws, NULL,            v_publisher_id,
       'platform_fee', v_amount_pf,
       v_url, v_catalog_id, v_grant_id, v_bot, v_subscription, p_api_key_id,
       'Platform fee');
  END LOOP;

  v_grants := (
    SELECT COALESCE(jsonb_agg(
      CASE
        WHEN (g->>'cached')::BOOLEAN THEN
          g - '_price' - '_publisher' - '_catalog' - '_ttl'
            - '_amount_content' - '_amount_sub_manager' - '_amount_platform'
        ELSE
          jsonb_build_object(
            'url',        g->>'url',
            'grant_id',   (SELECT id         FROM public.access_grants
                            WHERE api_key_id = p_api_key_id AND url = g->>'url'),
            'expires_at', (SELECT expires_at FROM public.access_grants
                            WHERE api_key_id = p_api_key_id AND url = g->>'url'),
            'cached',     false
          )
      END
    ), '[]'::JSONB)
    FROM jsonb_array_elements(v_grants) AS g
  );

  RETURN jsonb_build_object(
    'success',     true,
    'new_balance', v_new_balance,
    'grants',      v_grants
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.authorize_and_debit_batch(UUID, JSONB) TO authenticated;


COMMIT;


-- ============================================================================
-- ROLLBACK (manual — irreversible TRUNCATE on api_keys)
-- ============================================================================
-- See migration 040 + 041 + 042 for the previous network-based schema and
-- RPC body. Re-apply those after dropping the access_settings additions:
--   DROP TRIGGER + FUNCTION trg_api_keys_validate_bot_matches_access_settings;
--   ALTER TABLE api_keys DROP COLUMN access_settings_id;
--   DROP TABLE access_settings_catalogs;
--   DROP TABLE access_settings;
--   DROP FUNCTION touch_access_settings_updated_at();
--   DROP FUNCTION validate_access_settings_catalog();
--   DROP FUNCTION validate_access_settings_bot();
--   ALTER TABLE workspaces DROP COLUMN referral_workspace_id;
-- ============================================================================
